### PR TITLE
New Configuration Panel, New option quality level....

### PR DESCRIPTION
**Pull request by tomashalac**
+ Removed configuration box at start
+ New Configuration Panel
+  New option quality level

image

### CODE REVIEW

**Comment by Zaphyk** [comment]
What does quality do exactly? And why is it needed?

**Comment by tomashalac** [comment]
This was already implemented when you open the game, now is in a menu ingame.

More information about quality settings: [https://docs.unity3d.com/Manual/class-QualitySettings.html](https://docs.unity3d.com/Manual/class-QualitySettings.html)

**Comment by Zaphyk** [comment]
How does it look when on the main menu and on the score menu?

**Comment by Zaphyk** [comment]
This configuration panel is not needed and will take away from the simplistic style the game tries to achieve.

**Pull request closed without merging**
